### ISSUE TITLE
add hls output 

### ISSUE THREAD

**Issue by NH-Networks** [iebb/F1WebViewer-SelfHosted#1]
that would be nice :)

**Comment by ricky732** [comment]
Can you make a quick tutorial about how to make the self-hosting?

**Comment by iebb** [comment]
> Can you make a quick tutorial about how to make the self-hosting?

@ricky732 download [f1wvp-windows-amd64.exe](https://github.com/iebb/F1WebViewer-SelfHosted/releases/download/v0.0.1/f1wvp-windows-amd64.exe) from Releases, and run it. A browser window would open

**Comment by ricky732** [comment]
It does not load the events!! When I select a year, it does not load any GP

**Comment by iebb** [comment]
> It does not load the events!! When I select a year, it does not load any GP

any console outputs?

**Comment by ricky732** [comment]
![issue](https://user-images.githubusercontent.com/46622560/162498404-8e0317a4-21f7-4757-afb6-abbd48d3e112.png)

This...

**Comment by iebb** [comment]
@ricky732 the browser console?
