### ISSUE TITLE
`Cannot read properties of undefined (reading 'Protection')` when logging in

### ISSUE THREAD

**Issue by jerichosy** [iebb/F1WebViewer-SelfHosted#14]
Specifically this error `Cannot read properties of undefined (reading 'Protection')` during log in pops up [in line 117 of F1-Web-Viewer/src/store/index.js](https://github.com/iebb/F1-Web-Viewer/blob/a083a3431fbc5ade75068a3fe6b0459174b7bca9/src/store/index.js#L117).

I assume it has to do with the ff. unsuccessful query before even logging in
```
GET https://f1-api.jeb.nom.za/6657193977244c13 net::ERR_NAME_NOT_RESOLVED
```
It looks like DNS queries to [jeb.nom.za](https://jeb.nom.za/) and [f1-api.jeb.nom.za](https://f1-api.jeb.nom.za/) results in NXDOMAIN even when I query from other servers like [dnschecker.org](https://dnschecker.org/#A/f1-api.jeb.nom.za)

**Comment by s0fax** [comment]
Seems the same problem as #13.
The "new" authentication proxy instance to get the token from last year no longer seems to be available.
