### ISSUE TITLE
视频卡在加载

### ISSUE THREAD

**Issue by SkeletoNCY** [iebb/F1WebViewer-SelfHosted#3]
我下载了release中预编译的exe并在我的美国的azure服务器上运行他，但是我在本地一直观看视频一直在加载。
后端有"http: proxy error: context canceled"的提示

**Comment by iebb** [comment]
是直播的问题还是旧视频也有问题？

**Comment by SkeletoNCY** [comment]
两者都有问题

**Comment by iebb** [comment]
完全无法播放还是能看几秒？控制台里面有在下载mp4吗

**Comment by iebb** [comment]
确认了一下应该是 non-secure context 不支持 DRM，目前可以考虑套一层 nginx / apache 来转发？

**Comment by iebb** [comment]
@SkeletoNCY 试试新版，有内置的 let's encrypt 和自签名两种可选，可能会方便点

**Comment by SkeletoNCY** [comment]
> @SketoNCY新版，有编组的 let's encrypt 和自签名选择，可能会方便点

感谢大佬的回复，我在本地挂代理运行这个项目是可以正常播放的，emmm不管怎么说也算是解决了？不过前段时间有点忙就没怎么看github，不过还是感谢大佬啦xD

**Comment by iebb** [comment]
@SkeletoNCY 我一开始也没意识到，后来发现死活不请求WideVine，最后发现EME得要在secure context下面才能跑 😬
