### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by koevoet1221** [iebb/F1WebViewer-SelfHosted#7]
Hi, I’ve been trying to get this to work but every time the site will remain empty after login. I’m hosting it on my server using -self-sign and -listen 0.0.0.0:13331, the server is a vm on debian bullseye with proxmox as hypervisor. I’ve got the latest version and i’ve also tried using the -login and -password, I don’t have to login anymore but still a blank page. I’ve tried multiple clients, iPad, (android) phone and desktop (firefox). Ive also tried running the binary on my desktop without any tags with the same result. My f1tv subscription is the pro one. I’ve been using the binary (the linux amd64 one) you’ve provided on the releases.
Any idea how to fix this? 
thanks in advance
![3E51909C-554A-4D7F-B9D8-FFB188B9A705](https://user-images.githubusercontent.com/76625701/169653983-e40b618b-fae1-4279-ad9d-a739739fae46.jpeg)

**Comment by koevoet1221** [comment]
Its my fault (as always xD). For anyone in the future make sure you check that you have pihole or an other adblocker disabled. I havent yet found out what exactly needs to be unblocked, ill add that when I do.

**Comment by iebb** [comment]
If there's anything would collide with AdBlocker please let me know 🤤

**Comment by koevoet1221** [comment]
It took me a long time to find it since somehow it’s only required once on the client, even if you host it on a completely different server, and it’s only needed the first time you load the site.
fonts.googleapis.com
was blocked and only needs to be unblocked when you first load the site.

**Comment by iebb** [comment]
> It took me a long time to find it since somehow it’s only required once on the client, even if you host it on a completely different server if it was unblocked on the other one it works, only clearing the browser gets the blank page back. fonts.googleapis.com was blocked and only needs to be unblocked when you first load the site.

why a blocker would block custom fonts... really curious

**Comment by koevoet1221** [comment]
I’ve checked my host lists and this is the one that has its blocked:
https://block.energized.pro/extensions/xtreme/formats/hosts
guess they call it extreme for a reason  xD
