### ISSUE TITLE
Error on opening V0.2.0

### ISSUE THREAD

**Issue by Placemaster** [iebb/F1WebViewer-SelfHosted#9]
I tried running version 0.2.0 locally on my MacBook Air. I do get the following error after entering go run main.go

`# command-line-arguments
./main.go:89:44: undefined: handleLogin
./main.go:113:21: undefined: GetSelfSignedCertificate
note: module requires Go 1.17
`

How to resolve the issue?

**Comment by iebb** [comment]
are you using pre-built binary or just running the go file?

you are supposed to run "go run ." instead of "go run main.go" now

**Comment by Placemaster** [comment]
I have downloaded the F1WebViewer-SelfHosted-0.2.0.tar.gz file. When trying to run it with the command go run it does not start and do get the following error: `go run: no go files listed`

Also with go run main.go it does not run. Error code 
```
# command-line-arguments
./main.go:89:44: undefined: handleLogin
./main.go:113:21: undefined: GetSelfSignedCertificate
note: module requires Go 1.17
```

**Comment by iebb** [comment]
> I have downloaded the F1WebViewer-SelfHosted-0.2.0.tar.gz file. When trying to run it with the command go run it does not start and do get the following error: `go run: no go files listed`
> 
> Also with go run main.go it does not run. Error code
> 
> ```
> # command-line-arguments
> ./main.go:89:44: undefined: handleLogin
> ./main.go:113:21: undefined: GetSelfSignedCertificate
> note: module requires Go 1.17
> ```

add a dot after, `go run .`

**Comment by Placemaster** [comment]
with the . it is working.
Thanks!
